 const dummyTickets = [
    {
        ticketNumber: 1,
        description: 'Electrical issue in Unit 1',
        status: 'Open',
        date: '2023-12-01',
        type: 'ac',
        unitNumber: '1',
        propertyName: 'Nairobi Apartments',
    },
    {
        ticketNumber: 2,
        description: 'Light fixture replacement in Unit 2',
        status: 'In Progress',
        date: '2023-12-02',
        type: 'electrical',
        unitNumber: '2',
        propertyName: 'Nairobi Apartments',
    },
    {
        ticketNumber: 3,
        description: 'Leaking faucet in Unit 3',
        status: 'Resolved',
        date: '2023-12-03',
        type: 'plumbing',
        unitNumber: '3',
        propertyName: 'Nairobi Apartments',
    },
    {
        ticketNumber: 4,
        description: 'Electrical wiring inspection in Unit 4',
        status: 'Closed',
        date: '2023-12-04',
        type: 'electrical',
        unitNumber: '4',
        propertyName: 'Nairobi Apartments',
    },
    {
        ticketNumber: 5,
        description: 'Paint touch-up needed in Unit 5',
        status: 'Open',
        date: '2023-12-05',
        type: 'general',
        unitNumber: '5',
        propertyName: 'Nairobi Apartments',
    },
    {
        ticketNumber: 6,
        description: 'AC filter replacement in Unit 6',
        status: 'In Progress',
        date: '2023-12-06',
        type: 'ac',
        unitNumber: '6',
        propertyName: 'Nairobi Apartments',
    },
    {
        ticketNumber: 7,
        description: 'Window repair in Unit 7',
        status: 'Resolved',
        date: '2023-12-07',
        type: 'ac',
        unitNumber: '7',
        propertyName: 'Nairobi Apartments',
    },
    {
        ticketNumber: 8,
        description: 'Plumbing inspection in Unit 8',
        status: 'Closed',
        date: '2023-12-08',
        type: 'ac',
        unitNumber: '8',
        propertyName: 'Nairobi Apartments',
    },
    {
        ticketNumber: 9,
        description: 'Fridge repair in Unit 9',
        status: 'Open',
        date: '2023-12-09',
        type: 'general',
        unitNumber: '9',
        propertyName: 'Nairobi Apartments',
    },
    {
        ticketNumber: 10,
        description: 'AC duct cleaning in Unit 10',
        status: 'In Progress',
        date: '2023-12-10',
        type: 'ac',
        unitNumber: '10',
        propertyName: 'Nairobi Apartments',
    },
    // Continue adding tickets up to 100...

{
    ticketNumber: 11,
    description: 'Clogged drain in Unit 11',
    status: 'Open',
    date: '2023-12-11',
    type: 'plumbing',
    unitNumber: '11',
    propertyName: 'Nairobi Apartments',
},
{
    ticketNumber: 12,
    description: 'Broken window in Unit 12',
    status: 'In Progress',
    date: '2023-12-12',
    type: 'general',
    unitNumber: '12',
    propertyName: 'Nairobi Apartments',
},
{
    ticketNumber: 13,
    description: 'Leaking roof in Unit 13',
    status: 'Resolved',
    date: '2023-12-13',
    type: 'general',
    unitNumber: '13',
    propertyName: 'Nairobi Apartments',
},
{
    ticketNumber: 14,
    description: 'Faulty thermostat in Unit 14',
    status: 'Closed',
    date: '2023-12-14',
    type: 'ac',
    unitNumber: '14',
    propertyName: 'Nairobi Apartments',
},
{
    ticketNumber: 15,
    description: 'Mold removal in Unit 15',
    status: 'Open',
    date: '2023-12-15',
    type: 'general',
    unitNumber: '15',
    propertyName: 'Nairobi Apartments',
},
{
    ticketNumber: 16,
    description: 'Plumbing leak in Unit 16',
    status: 'In Progress',
    date: '2023-12-16',
    type: 'plumbing',
    unitNumber: '16',
    propertyName: 'Nairobi Apartments',
},
{
    ticketNumber: 17,
    description: 'Broken door handle in Unit 17',
    status: 'Resolved',
    date: '2023-12-17',
    type: 'general',
    unitNumber: '17',
    propertyName: 'Nairobi Apartments',
},
{
    ticketNumber: 18,
    description: 'Electrical outlet not working in Unit 18',
    status: 'Closed',
    date: '2023-12-18',
    type: 'electrical',
    unitNumber: '18',
    propertyName: 'Nairobi Apartments',
},
{
    ticketNumber: 19,
    description: 'Water heater repair in Unit 19',
    status: 'Open',
    date: '2023-12-19',
    type: 'plumbing',
    unitNumber: '19',
    propertyName: 'Nairobi Apartments',
},
{
    ticketNumber: 20,
    description: 'AC unit replacement in Unit 20',
    status: 'In Progress',
    date: '2023-12-20',
    type: 'ac',
    unitNumber: '20',
    propertyName: 'Nairobi Apartments',
},
];// Continue adding tickets up to 100...

export default dummyTickets;